#                                            Basic NumPy Operations

### 1. Import numpy as np and see the version

In [1]:
import numpy as np

In [2]:
print(np.version.version)

1.18.5


### 2. To create a 1D array

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3. To create a boolean array

In [4]:
np.zeros((3,3), dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

### 4. To extract items that satisfy a given condition from 1D array

In [5]:
np.full((3,3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### 5. To replace items that satisfy a condition with another value in numpy array

In [6]:
a=np.arange(10)
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

### 6. To replace items that satisfy a condition without affecting the original array

In [7]:
a=np.arange(10)
a[a % 2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 7. To reshape an array

In [8]:
a=np.arange(10)
b=np.where(a%2==1,-1,a)
print(a)
b

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

### 8. To stack two arrays vertically

In [9]:
a=np.arange(10)
a.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### 9. To stack two arrays horizontally

In [10]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 10. To generate custom sequences in numpy without hardcoding

In [11]:
a=np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### 11. To get the common items between two python numpy arrays

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

### 12. To remove from one array those items that exist in another

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.setdiff1d(a,b)

array([1, 3, 5, 6])

### 13. To get the positions where elements of two arrays match

In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### 14. To extract all numbers between a given range from a numpy array

In [15]:
a=np.arange(15)
a[(a>5)&(a<10)]

array([6, 7, 8, 9])

### 15. To make a python function that handles scalars to work on numpy arrays

In [16]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[int])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

### 16. To swap two columns in a 2d numpy array

In [17]:
a=np.arange(9).reshape(3,3)
a
a[:,[1,0,2]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 17. To swap two rows in a 2d numpy array

In [18]:
a=np.arange(9).reshape(3,3)
a
a[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 18. To reverse the rows of a 2D array

In [19]:
a=np.arange(9).reshape(3,3)
a
a[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

### 19. To reverse the columns of a 2D array

In [20]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### 20. To create a 2D array containing random floats between 5 and 10

In [21]:
a=np.arange(9)
b=np.random.uniform(5,10,size=(5,3))
print(b)

[[5.47440115 8.0318709  6.8206504 ]
 [6.90571674 6.96599611 8.83826159]
 [5.56376824 7.65656724 5.33982519]
 [9.19908712 8.30263517 8.48027195]
 [5.60919692 9.63968819 8.74956605]]


### 21. To pretty print a numpy array by suppressing the scientific notation (like 1e10)

In [22]:
np.random.seed(100)
a=np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)
a

array([[0.0005434 , 0.00027837, 0.00042452],
       [0.00084478, 0.00000472, 0.00012157],
       [0.00067075, 0.00082585, 0.00013671]])

### 22. To print only 3 decimal places in python numpy array

In [23]:
a=np.random.random([5,3])
np.set_printoptions(precision=2)
a

array([[0.58, 0.89, 0.21],
       [0.19, 0.11, 0.22],
       [0.98, 0.81, 0.17],
       [0.82, 0.27, 0.43],
       [0.94, 0.82, 0.34]])

### 23. To limit the number of items printed in output of numpy array

In [24]:
np.set_printoptions(threshold=6)
a = np.arange(15)

# Solution
np.set_printoptions(threshold=np.inf)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 24. To extract a particular column from 1D array of tuples

In [25]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepa', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

### 25. To convert a 1d array of tuples to a 2d numpy array

In [26]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

# Solution:
species = np.array([row[4] for row in iris_1d])
species[:4]

(150,)


<ipython-input-26-5c3004e07ce3>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa'],
      dtype='|S18')

### 26. To compute the mean, median, standard deviation of a numpy array

In [27]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None,usecols=(1,2,3))
iris_1d[:3]

# Solution:
#species = np.array([row[4] for row in iris_1d])
#species[:5]

array([[3.5, 1.4, 0.2],
       [3. , 1.4, 0.2],
       [3.2, 1.3, 0.2]])

### 27. To normalize an array so the values range exactly between 0 and 1

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
s=np.genfromtxt(url,delimiter=',',dtype=None,usecols=[0])
s[:5]
m,me,sd=np.mean(s),np.median(s),np.std(s)
print(m,me,sd)

5.843333333333334 5.8 0.8253012917851409


<ipython-input-28-28757a991e55>:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)


### 28. To compute the softmax score

In [29]:
np.set_printoptions(threshold=1000)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=float)
s=np.genfromtxt(url,delimiter=',',dtype=float,usecols=[0])
smax,smin=s.max(),s.min()
S= (s-smin)/(s.ptp())
print(S)

[0.22 0.17 0.11 0.08 0.19 0.31 0.08 0.19 0.03 0.17 0.31 0.14 0.14 0.
 0.42 0.39 0.31 0.22 0.39 0.22 0.31 0.22 0.08 0.22 0.14 0.19 0.19 0.25
 0.25 0.11 0.14 0.31 0.25 0.33 0.17 0.19 0.33 0.17 0.03 0.22 0.19 0.06
 0.03 0.19 0.22 0.14 0.22 0.08 0.28 0.19 0.75 0.58 0.72 0.33 0.61 0.39
 0.56 0.17 0.64 0.25 0.19 0.44 0.47 0.5  0.36 0.67 0.36 0.42 0.53 0.36
 0.44 0.5  0.56 0.5  0.58 0.64 0.69 0.67 0.47 0.39 0.33 0.33 0.42 0.47
 0.31 0.47 0.67 0.56 0.36 0.33 0.33 0.5  0.42 0.19 0.36 0.39 0.39 0.53
 0.22 0.39 0.56 0.42 0.78 0.56 0.61 0.92 0.17 0.83 0.67 0.81 0.61 0.58
 0.69 0.39 0.42 0.58 0.61 0.94 0.94 0.47 0.72 0.36 0.94 0.56 0.67 0.81
 0.53 0.5  0.58 0.81 0.86 1.   0.58 0.56 0.5  0.94 0.56 0.58 0.47 0.72
 0.67 0.72 0.42 0.69 0.67 0.67 0.56 0.61 0.53 0.44]


### 29. To sum a 1D array

In [30]:
x=np.arange(6)
np.add.reduce(x)

15

### 30. To calculate mode

In [31]:
from scipy import stats
x=np.arange(6)
stats.mode(x)

ModeResult(mode=array([0]), count=array([1]))